[package]
name = "infopanel"
version = "0.1.0"
edition = "2021"
authors = ["Yves Bruckmayer <y.bruckmayer@gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
log = "0.4.20"
log4rs = "1.2.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
