appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {M} {m}{n})}"
  file_logger:
    kind: rolling_file
    path: "log/infopanel.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {M} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 250kb
      roller:
        kind: delete
root:
  level: info
  appenders:
    - stdout
    - file_logger
